Network.py: Use str instead of integer
cdir is '24tr', so str type.

File "/usr/lib/enigma2/python/Components/Network.py", line 704, in calc_netmask
    print('[Network] cidr invalid: %d' % cidr)
TypeError: %d format: a number is required, not str