HdmiCec.py: Use try/except instead of assert
HdmiCec.instance must be defined before we can use assert.

File "/usr/lib/enigma2/python/Components/HdmiCec.py", line 93, in __init__
    assert not HdmiCec.instance, "only one HdmiCec instance is allowed!"
AttributeError: type object 'HdmiCec' has no attribute 'instance'